### ISSUE TITLE
add a `contributing.md` file

### ISSUE THREAD

**Issue by arthurvr** [jugoncalves/awesome-answers#17]
With clear guidelines what answers can be added to the list, how the list should be structured and how people can contribute.

You can use https://github.com/sindresorhus/awesome/blob/master/contributing.md as inspiration.

**Comment by cyberglot** [comment]
That's also good. I'll have a look.

**Comment by cyberglot** [comment]
:+1: :tada:

**Comment by arthurvr** [comment]
Thanks!
