### ISSUE TITLE
My answer from Code Review Stack Exchange

### ISSUE THREAD

**Issue by bitemyapp** [jugoncalves/awesome-answers#2]
Can serve as a demonstration of type-driven reasoning in Haskell, point-free, etc.

http://codereview.stackexchange.com/questions/57843/update-map-in-haskell/57850#57850

**Comment by cyberglot** [comment]
@bitemyapp thanks :heart: if you got any more cool answers or have any bookmarked somewhere, pls open an issue/PR or ping me on twitter :smile:
